---
title: "cschmidt-vis_assignment2"
author: "cschmidt"
date: "9/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Step 1
Load Relevant Libraries
```{r}
library(ggplot2)
library(sf)
library(rnaturalearth)
library(tidyverse)
library(tidycensus)
library(ggspatial)
library(cartogram)
library(ggthemes)
```

##Step 2
Test: Print World Map + Download Additional Package Whatnots
```{r}
library(rgeos)
world <- ne_countries(scale = 50, returnclass = "sf") 
world_map <- ggplot(world) +
  geom_sf() +
  theme_bw()
world_map

US_states <- ne_states(country = "United States of America", 
                       returnclass = "sf") %>%
  filter(name != "Alaska",
         name != "Hawaii")

US_map <- ggplot(US_states) +
  geom_sf() +
  theme_bw()


```
##Step 3: Assignment Projections
#Projection 1: United States w/ USA_AEA

Projections
```{r}
USA_AEA <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=clrk66 +units=m +no_defs"
SeaIceSouth <- "+proj=stere +lat_0=-90 +lat_ts=-70 +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378273 +b=6356889.449 +units=m +no_defs"
NZGD2000 <- "+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"

states_transformed <- US_states %>%
  st_transform(crs = USA_AEA)

```

Data
```{r}
covid_us<-read.csv("csv.csv")

covid_states <-states_transformed %>%
  left_join(covid_us, by = c("name" = "X")) %>%
  mutate(pop = 100000 * Confirmed / Incident_Rate) %>%
  select(name, pop, Confirmed, Deaths, Recovered, Active)
```


USA_AEA
```{r}

ggplot(covid_states, aes(fill = Confirmed)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(
    name = "Number of\nconfirmed\nCOVID-19\ncases as of\nAugust 6, 2020",
    breaks = seq(100000, 500000, by = 100000),
    labels = formatC(seq(100000, 500000, by = 100000), 
                     big.mark = ",", format = "f", digits = 0)) +
  theme_map() +
  coord_sf(crs = USA_AEA) +
  theme(legend.background = element_blank())
```
NZGD2000 Squishy
```{r}
states_transformed <- US_states %>%
  st_transform(crs = NZGD2000)

covid_cartogram_cont <- covid_states %>%
  cartogram_cont("pop")

ggplot(covid_cartogram_cont, aes(fill = Active)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(
    name = "Number of confirmed\nCOVID-19 cases\nas of August 6, 2020",
    breaks = seq(100000, 500000, by = 100000),
    labels = formatC(seq(100000, 500000, by = 100000), 
                     big.mark = ",", format = "f", digits = 0)) +
  theme_map() +
  coord_sf(crs = NZGD2000) +
  theme(legend.background = element_blank())
```
SeaIceSouth Prop Symbol
```{r}
covid_centeroids <- covid_states %>%
  st_centroid()

ggplot(states_transformed) +
  geom_sf(fill = NA, color = "gray") +
  geom_sf(data = covid_centeroids, 
          aes(size = Confirmed),
          alpha = 0.5, color = "red") +
  scale_size_continuous(name = "Number of confirmed\nCOVID-19 cases as of\nAugust 6, 2020",
    breaks = seq(100000, 500000, by = 100000),
    labels = formatC(seq(100000, 500000, by = 100000), 
                     big.mark = ",", format = "f", digits = 0),
    range = c(0, 20)) +
  coord_sf(crs = SeaIceSouth) +
  theme_void() 

```

